### ISSUE TITLE
Add "is in remote control" call as a dashboard service

### ISSUE THREAD

**Issue by urfeex** [UniversalRobots/Universal_Robots_ROS2_Driver#1195]
### Feature summary

As discussed in #1191 it would be nice to have a service for querying the remote_control mode state. This is implemented in the dashboard server and in the ur_client_library, but not in the ROS wrapper.

### Related issues
ur_client_library API call: https://github.com/UniversalRobots/Universal_Robots_Client_Library/blob/4daad9b890943cfc22bee74df7ac8a069ca3ed6e/include/ur_client_library/ur/dashboard_client.h#L266

### Tasks
*To complete this issue involves*
- [ ] Implement the feature
- [ ] Make documentation
- [ ] Make Unit test
- [ ] Test on real hardware
